### ISSUE TITLE
Internal Error + not falling back

### ISSUE THREAD

**Issue by jenslys** [remorses/ai-fallback#2]
Hi, been trying this but it dosent seem to fallback for a certain error type; Trying with Groq and Google, and its failing with the Groq model, but not falling back to Googles.

```ts
import { createFallback } from "ai-fallback";
import { groq } from "@ai-sdk/groq";
import { google } from "@ai-sdk/google";
import { log } from "next-axiom";

export const aiModel = createFallback({
  models: [groq("llama3-8b-8192"), google("gemini-1.5-flash-002")],
  retryAfterOutput: true,
  onError: (error, modelId) => {
    log.error("[AI] Error with model, falling back to next model", {
      modelId,
      error: error instanceof Error ? error.message : "Unknown error",
    });
  },
  modelResetInterval: 60000,
});
```

error:

```
{
  "error": "Internal server error",
  "message": "Please reduce the length of the messages or completion.",
  "type": "INTERNAL_ERROR",
}
```

Note:
Changing Groq model fixes the original issue, but it should still fallback to google, regardless of model(?)

**Comment by remorses** [comment]
Can you check you are using the latest version? This error should be caught, otherwise should be an easy fix

**Comment by remorses** [comment]
Is the JSON you pasted the fields in the Error object that is thrown?

**Comment by jenslys** [comment]
Using latest version.

The error message being thrown is:
Name: `AI_APICallError`
Message: `Please reduce the length of the messages or completion.`

**Comment by jenslys** [comment]
There is also the error: `Failed to generate JSON. Please adjust your prompt. See \'failed_generation\' for more details.`

**Comment by remorses** [comment]
I added a few more errors that are automatically handled but i don't want to add 400 kind of errors like `Please reduce the length of the messages or completion.`, this is because these errors should be cought during development and adding them would hide them from you

Instead you can pass `shouldRetryThisError` and handle them yourself

```ts
const model = createFallback({
        models: [
            openai('non-existent-model'),
            anthropic('claude-3-haiku-20240307'),
        ],
        shouldRetryThisError: (error) => {
            return error.message.toLowerCase().includes('please reduce')
        },
    })
```
